name: Bug Report
description: File a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "## Bug Report\nPlease fill out the information below to help us address the issue."
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of what the bug is.
      placeholder: "Describe the bug..."
    validations:
      required: true
  - type: checkboxes
    id: tool
    attributes:
      label: Tool
      description: Please specify which tool faces the issue.
      options:
        - label: All
        - label: Listicle
        - label: Music Cover Maker
        - label: Other
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: "1. Run with '...'\n2. Use the tool '...'\n3. Scroll down to '...'\n4. See error"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Please describe the behavior you are expecting.
      placeholder: "Explain the expected outcome..."
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: "Upload or drag & drop screenshots here..."
    validations:
      required: false
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: "What environments are you seeing the problem on?"
      options:
        - Docker
        - Windows
        - Mac
        - Linux
        - Other
      multiple: true
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: "What browsers are you seeing the problem on?"
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Vivaldi
        - Other
      multiple: true
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: "Any additional context..."
    validations:
      required: false
  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution / Workaround
      description: If you have an idea about what is causing the issue or how to fix it, please describe it here.
      placeholder: "Describe any potential solutions or workarounds..."
    validations:
      required: false