name: Question
description: Ask a question related to the project
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: "## Ask Your Question\nPlease provide details below to get a quick and accurate response."
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Write your question here. Be as specific as possible.
      placeholder: "What is your question?"
    validations:
      required: true
  - type: textarea
    id: relevant-details
    attributes:
      label: Relevant Details
      description: Include any information that might help in understanding your question better.
      placeholder: "Version of the project, operating system, context of use case, etc."
    validations:
      required: true
  - type: checkboxes
    id: tool
    attributes:
      label: Tool
      description: If relevant, please specify which tool your question is related to.
      options:
        - label: Listicle
        - label: Music Cover Maker
  - type: textarea
    id: what-youve-tried
    attributes:
      label: What You've Tried
      description: Detail what you've tried in order to answer your question.
      placeholder: "Describe what you have attempted so far..."
    validations:
      required: false
  - type: textarea
    id: expected-information
    attributes:
      label: Expected Information or Outcome
      description: Describe what kind of answer or outcome you're expecting.
      placeholder: "Are you looking for a solution, documentation clarification, best practices, etc.?"
    validations:
      required: true
  - type: textarea
    id: screenshots-or-code
    attributes:
      label: Screenshots or Code Snippets
      description: If applicable, add screenshots or code snippets to illustrate your question.
      placeholder: "Upload or paste your screenshots or code here..."
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the question.
      placeholder: "Any additional context, related to previous issues, discussions, etc."
    validations:
      required: false
